### ISSUE TITLE
Invalid escape sequence \u. UTF-16 surrogates are not allowed in strings

### ISSUE THREAD

**Issue by dpavicic** [massiveinteractive/haxe-react#127]
Hi,
I'm trying to compile to-do example but build fails with error in react.jsx.HtmlEntities:
Invalid escape sequence \u. UTF-16 surrogates are not allowed in strings

I'm using latest Haxe 4,rc3

**Comment by kLabz** [comment]
Should be fixed in latest haxe-react git

**Comment by dpavicic** [comment]
Just tried with haxe-react git; the same issue still occurs. ( Haxe 4.rc3 ).
Also tried with haxe 3.4.3. Builds and works fine.

If I remove \u in HtmlEntities.map it seems to work fine.

Also there is deprectiation warning for js.lib.Error in RectComponent and ReactPropTypes.

Cheers,
D.

**Comment by kLabz** [comment]
Doesn't seem right, HtmlEntities does not exist any more on latest git

**Comment by dpavicic** [comment]
Uh, right. Sorry. My bad. I installed git one as  'haxe-react' while still having haxelib one as 'react'.  I removed them and installed git only the git one and works just fine.

Thank you!
